version: 0.2

phases:
  install:
      runtime-versions:
        python: 3.9
      commands:
        - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Checking which microservices need to be built...
      - |
        if git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION | grep 'consultar_incidentes/'; then
          export BUILD_MS1=true
          echo Logging in to Amazon ECR...
        fi
      - |
        if git diff --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION | grep 'crear_incidentes/'; then
          export BUILD_MS2=true
          echo Logging in to Amazon ECR 2...
        fi
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 682033469251.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - |
        if [ "$BUILD_MS1" == "true" ]; then
          echo "Building consultar_incidentes ..."
          cd consultar_incidentes
          docker build -t abcallproyectofinal1 .
          docker tag abcallproyectofinal1:latest 682033469251.dkr.ecr.us-east-2.amazonaws.com/abcallproyectofinal1:latest
          cd ..
        fi
      - |
        if [ "$BUILD_MS2" == "true" ]; then
          echo "Building crear_incidentes ..."
          cd crear_incidentes
          docker build -t abcallproyectofinal1crear .
          docker tag abcallproyectofinal1crear:latest 682033469251.dkr.ecr.us-east-2.amazonaws.com/abcallproyectofinal1crear:latest
          cd ..
        fi
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Post-build phase"
      - |
        if [ "$BUILD_MS1" == "true" ]; then
          echo "Pushing consultar_incidentes to ECR..."
          docker push 682033469251.dkr.ecr.us-east-2.amazonaws.com/abcallproyectofinal1:latest
          echo Writing Image Definitions file...
          printf '[{"name":"Container-app-abcall","682033469251.dkr.ecr.us-east-2.amazonaws.com/abcallproyectofinal1:latest"}]' > imagedefinitions.json
          printf '{"ImageURI":"682033469251.dkr.ecr.us-east-2.amazonaws.com/abcallproyectofinal1:latest"}' > imageDetail.json
          cat ../imagedefinitions.json  
        fi
      - |
        if [ "$BUILD_MS2" == "true" ]; then
          echo "Pushing crear_incidentes to ECR..."
          docker push 682033469251.dkr.ecr.us-east-2.amazonaws.com/abcallproyectofinal1crear:latest
          echo Writing Image Definitions file...
          printf '[{"name":"Container-app-abcall-crear","682033469251.dkr.ecr.us-east-2.amazonaws.com/abcallproyectofinal1crear:latest"}]' > imagedefinitions.json
          printf '{"ImageURI":"682033469251.dkr.ecr.us-east-2.amazonaws.com/abcallproyectofinal1crear:latest"}' > imageDetail.json
          cat ../imagedefinitions2.json  
        fi
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json